### ISSUE TITLE
Parse into JSON.

### ISSUE THREAD

**Issue by PollieDev** [SaltieRL/carball#156]
Hey,

I'm not familiar at all with Python and their structure. So this might be more a Python related question than a Carball related question. Hard to tell:

My goal is to parse a replay into a JSON that includes the analysis etc...
Currently I'm able to load the replay perfectly and let it parse it. Now I want to write that data to a .json file. Looked things up and found the `json.dumps` but it's providing me the following error:
`TypeError: Object of type 'Game' is not JSON serializable`

I pretty much understand the error but not sure how I would go about on parsing that into JSON.
Any help or clue towards the correct answer is very welcome.

Kind regards,
Pollie

**Comment by twobackfromtheend** [comment]
We use the protocol buffers format detailed here to store our stats: https://developers.google.com/protocol-buffers/

The advantage is that our formats are backward compatible and somewhat self-documenting (https://github.com/SaltieRL/carball/tree/master/api). However the thing doesn't support jsonifying using the standard library json and has its own functions to do such things.

Use something like with ```py
open(os.path.join('output.pts'), 'wb') as fo:
    analysis.write_proto_out_to_file(fo)```
(as written in our readme haha) to convert it to a format that can be read by the protobuf library in any of their supported languages, or call `json = MessageToJson(analysis.protobuf_game)` and write that out if you want it in (human-readable) json.
https://developers.google.com/protocol-buffers/docs/reference/python/google.protobuf.json_format-module

**Comment by PollieDev** [comment]
Hey,

I saw the first part but was confused by what it returned.
Thank you very much for the link, that was exactly what I was looking for and it's working wonderfully.

Thank you for this and the previous answer on the other issue!
