### ISSUE TITLE
Rocket League update

### ISSUE THREAD

**Issue by sertalpbilal** [SaltieRL/carball#264]
After the new season update, `carball.analyze_replay_file` method is failing:

```
Error decoding frame: attribute unknown or not implemented: actor id / 
actor object id / attribute id: 140 / 286 / 57. found attribute TAGame.Car_TA:ReplicatedDemolishGoalExplosion (unknown to boxcars) on Archetypes.Car.Car_Default in 
network cache data. This is likely due to a rocket league update or an atypical replay. File a bug report! Context: on frame: 6751, last updated actor: (actor stream id / object id / name: 140 / 286 / Archetypes.Car.Car_Default, attribute stream id / object id / name: 41 / 244 / TAGame.RBActor_TA:ReplicatedRBState, attribute: 
RigidBody(RigidBody { sleeping: true, location: Vector3f { x: 633.45, y: -5121.8, z: 17.04 }, rotation: Quaternion { x: -0.0027000958, y: 0.00802476, z: 0.3173204, 
w: 0.9482806 }, linear_velocity: None, angular_velocity: None }))
```

**Comment by Sciguymjm** [comment]
Yup, reinstall carball and you should be good to go. I updated the parser
on Saturday.

**Comment by sertalpbilal** [comment]
`pip install carball` still produces the same problem.

You are referring to boxcars (boxcars-py), right?  I think latest boxcars-py on PyPI is version 0.1.12
https://pypi.org/project/boxcars-py/
I tried downloading the latest release on repository
https://github.com/SaltieRL/boxcars-py
but it doesn't seem like have any Linux binaries. Is there a way to use the latest version without building after downloading the .tar.gz file?

**Comment by Sciguymjm** [comment]
Upgrading boxcars-py should do it. `pip install boxcars-py --upgrade`

**Comment by sertalpbilal** [comment]
It worked, thanks a lot!
