### ISSUE TITLE
Season 5 Replays Fail to Parse

### ISSUE THREAD

**Issue by craziness924** [SaltieRL/carball#267]
Hello, I'm getting the following error when I attempt to parse a replay saved during Season 5 of F2P:

`Exception: Error decoding frame: attribute unknown or not implemented: actor id / actor object id / attribute id: 2 / 98 / 
24. found attribute TAGame.CarComponent_Dodge_TA:DodgeImpulse (unknown to boxcars) on Archetypes.CarComponents.CarComponent_Dodge in network cache data. This is likely due to a rocket league update or an atypical replay. File a bug report! Context: on frame: 159, last updated actor: (actor stream id / object id / name: 2 / 98 / Archetypes.CarComponents.CarComponent_Dodge, attribute stream id / object id / name: 22 / 91 / TAGame.CarComponent_TA:ReplicatedActive, attribute: Byte(3))`

Likely known that the replay format has changed, but I wanted to file a bug report as it says. Thank you.

**Comment by craziness924** [comment]
It was an issue with boxcars and boxcars-py, apologies. I'll post over there next time.

**Comment by dtracers** [comment]
It is good to let us know so we can update boxcars / boxcars-py locally
(or send us a PR with the updated versioning for carball!)

**Comment by craziness924** [comment]
I'd like to help out with updating boxcars-py to keep carball working, but I'm not sure how to build and test any edits I make on my end.
