### ISSUE TITLE
Duplicated replays when uploaded from multiple players

### ISSUE THREAD

**Issue by ravionn** [SaltieRL/carball#68]
When two players from the same match (same team for sure) upload a replay of the same match, both files are kept and displayed on the players.

Experienced with Bakkes Mod auto upload

E.g. https://calculated.gg/players/76561198026480940/match_history?page=1&limit=10 28/9/18, uploaded by 0312Penner (my mate) and Ravi(me)

**Comment by dtracers** [comment]
Thank you for the issue.

This has been fixed in the carball repo.
But has not been fixed in the Distributed replay repo.

I will close this here and open one in the other repo and link to this one.
